external-controller: 127.0.0.1:9090
secret: ""
bind-address: "*"
external-ui: yacd-gh-pages

port: 7890
socks-port: 7891
redir-port: 7892
tproxy-port: 7895
mixed-port: 1080

log-level: info
allow-lan: true
ipv6: false
interface-name: en0
mode: rule

dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - 1.1.1.1
    - 1.0.0.1
  nameserver:
    - 1.1.1.1 
    - 1.0.0.1 
    - tls://dns.rubyfish.cn:853 
    - https://1.1.1.1/dns-query 
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16

profile:
  store-selected: true
  store-fake-ip: true

proxy-providers:
  AKUN:
    type: http
    behavior: classical
    url: https://raw.githubusercontent.com/unthenamed/rules/main/akun.yaml
    path: "./akun.yaml"
    interval: 900
    health-check:
      enable: false
      url: http://www.gstatic.com/generate_204
      interval: 300

    

proxy-groups:

- name: MENU
  type: select
  proxies:
  - SELECT
  - BALANCING
  - BEST-PING
  - DIRECT

- name: SELECT
  type: select
  use:
  - AKUN

#Bundling apps
- name: BUNDLING
  type: select
  proxies:
  - DIRECT
  - MENU
  - BEST-PING
  - REJECT

#BLOCKADS
- name: ADS
  type: select
  proxies:
  - REJECT
  - DIRECT
  - MENU
  - BEST-PING


- name: BALANCING
  type: load-balance
  strategy: consistent-hashing
  disable-udp: false
  use:
  - AKUN
  url: https://cp.cloudflare.com/generate_204
  interval: '300'


- name: BEST-PING
  type: url-test
  tolerance: 100
  use:
  - AKUN
  url: https://cp.cloudflare.com/generate_204
  interval: '300'




rules:
#dst direct/rejetc
 - DST-PORT,7895,REJECT
 - DST-PORT,7892,REJECT
 - DST-PORT,7895,REJECT
 - DST-PORT,7892,REJECT
#ipcdr direct/reject
 - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
 - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
 - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
 - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
 - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
 - IP-CIDR6,::1/128,DIRECT,no-resolve
 - IP-CIDR6,fc00::/7,DIRECT,no-resolve
 - IP-CIDR6,fe80::/10,DIRECT,no-resolve
 - IP-CIDR6,fd00::/8,DIRECT,no-resolve
 - IP-CIDR,198.18.0.1/16,REJECT,no-resolve
 - RULE-SET,rule_lancidr,DIRECT
 - RULE-SET,direct,DIRECT
 - RULE-SET,rule_reject,REJECT
 - RULE-SET,rule_BlockAds,ADS
 - RULE-SET,rule_privacy,ADS
 - RULE-SET,rule_basicads,ADS


# Paket Ekstra Kuota Unlimited	
# 0,5GB	WhatsApp, LINE, TikTok, 
#		MusicMAX, & GamesMAX.
# 2/4GB	WhatsApp, LINE, Facebook, Instagram, TikTok, 
#		MAXstream, MusicMAX, & GamesMAX.
# 7GB	WhatsApp, LINE, Facebook, Instagram, TikTok, 
#		YouTube, MAXstream, MusicMAX, & GamesMAX.

#rules
 - RULE-SET,rule_whatsapp,BUNDLING
 - RULE-SET,rule_line,BUNDLING
 - RULE-SET,rule_tiktok,BUNDLING
 - RULE-SET,rule_messenger,BUNDLING
 - RULE-SET,rule_metaverse,BUNDLING
 - RULE-SET,rule_instagram,BUNDLING

 - MATCH,MENU

rule-providers:

  rule_lancidr:
    type: http
    behavior: ipcidr
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: "./rule_provider/rule_lancidr.yaml"
    interval: 86400

  direct:
    type: http
    behavior: classical
    path: "./rule_provider/direct.yaml"
    url: https://raw.githubusercontent.com/unthenamed/rules/main/direct.yaml
    interval: 86400

  rule_umum:
    type: http
    behavior: classical
    path: "./rule_provider/rule_umum.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_umum.yaml
    interval: 86400

  rule_Sosmed:
    type: http
    behavior: classical
    path: "./rule_provider/rule_sosmed.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_sosmed.yaml
    interval: 86400

  rule_videoconferences:
    type: http
    behavior: classical
    path: "./rule_provider/rule_videoconferences.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_videoconferences.yaml
    interval: 86400

  rule_line:
    type: http
    behavior: domain
    url: https://rules.kr328.app/line.yaml
    path: "./rule_provider/rule_line.yaml"
    interval: 86400

  rule_metaverse:
    type: http
    behavior: domain
    url: https://rules.kr328.app/facebook.yaml
    path: "./rule_provider/rule_metaverse.yaml"
    interval: 86400

  rule_whatsapp:
    type: http
    behavior: domain
    url: https://rules.kr328.app/whatsapp.yaml
    path: "./rule_provider/rule_whatsapp.yaml"
    interval: 86400

  rule_tiktok:
    type: http
    behavior: domain
    url: https://rules.kr328.app/tiktok.yaml
    path: "./rule_provider/rule_tiktok.yaml"
    interval: 86400

  rule_twitter:
    type: http
    behavior: domain
    url: https://rules.kr328.app/twitter.yaml
    path: "./rule_provider/rule_twitter.yaml"
    interval: 86400

  rule_Youtube:
    type: http
    behavior: domain
    url: https://rules.kr328.app/youtube.yaml
    path: "./rule_provider/rule_Youtube.yaml"
    interval: 86400

  rule_instagram:
    type: http
    behavior: domain
    url: https://rules.kr328.app/instagram.yaml
    path: "./rule_provider/rule_instagram.yaml"
    interval: 86400

  rule_messenger:
    type: http
    behavior: domain
    url: https://rules.kr328.app/messenger.yaml
    path: "./rule_provider/messenger.yaml"
    interval: 86400


#game rules
  rule_portgames:
    type: http
    behavior: classical
    path: "./rule_provider/rule_portgames.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_portgames.yaml
    interval: 86400

  rule_games:
    type: http
    behavior: domain
    url: https://rules.kr328.app/category-games.yaml
    path: "./rule_provider/rule_games.yaml"
    interval: 86400

  rule_Gaming:
    type: http
    behavior: classical
    path: "./rule_provider/rule_gaming.yaml"
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_gaming.yaml
    interval: 86400

#BLOCK ADS
  rule_BlockAds:
    type: http
    behavior: classical
    path: "./rule_provider/rule_BlockAds.yaml"
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Advertising/Advertising_Classical.yaml
    interval: 86400

  rule_reject:
    type: http
    behavior: domain
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: "./rule_provider/rule_reject.yaml"
    interval: 86400

  rule_privacy:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Privacy/Privacy_Classical.yaml
    path: "./rule_provider/rule_privacy.yaml"
    interval: 86400

  rule_basicads:
    type: http
    behavior: classical
    url: https://cdn.jsdelivr.net/gh/malikshi/open_clash@main/rule_provider/rule_basicads.yaml
    path: "./rule_provider/rule_basicads.yaml"
    interval: 86400
